app-name: 	        "Odin Kittens"

key:                "1da66afc4faef256174e133694c5dd03"

uecret:             "0b461cc867ca7639 "

user:               "kfuyiszq23 / Manuel S"

random-profile:     "https://www.flickr.com/photos/kvaidya/"

random-profile-id:  "27409143@N00"
